
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true
[env]
TERM = "xterm-256color"
[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 12

